video_path: data/frames/mallard-fly
save_dir: data/frames/mallard-fly/ddim_latents
max_number_of_frames: 24

n_timesteps: 999
prompt: Amazing quality, masterpiece, a mallard is walking on the grassland.
negative_prompt: ""
save_ddim_reconstruction: True