video_path: data/frames/Couple_Runner
save_dir: data/frames/Couple_Runner/ddim_latents
max_number_of_frames: 24

n_timesteps: 999
prompt: Amazing quality, masterpiece, two people are running on the street.
negative_prompt: ""
save_ddim_reconstruction: True