video_path: data/frames/van
save_dir: data/frames/van/ddim_latents
max_number_of_frames: 24

n_timesteps: 999
prompt: Amazing quality, masterpiece, a van is moving one the road.
negative_prompt: ""
save_ddim_reconstruction: True