video_path: data/frames/couple
save_dir: data/frames/couple/ddim_latents
max_number_of_frames: 24

n_timesteps: 999
prompt: Amazing quality, masterpiece, a man and a woman are walking under the sunset.
negative_prompt: ""
save_ddim_reconstruction: True