video_path: data/frames/helicopter
save_dir: data/frames/helicopter/ddim_latents
max_number_of_frames: 24

n_timesteps: 999
prompt: Amazing quality, masterpiece, a walking man and a spining helicopter
negative_prompt: ""
save_ddim_reconstruction: True