video_path: data/frames/cart
save_dir: data/frames/cart/ddim_latents
max_number_of_frames: 24

n_timesteps: 999
prompt: Amazing quality, masterpiece, two boys driving carts are racing.
negative_prompt: ""
save_ddim_reconstruction: True