video_path: data/frames/car_turn
save_dir: data/frames/car_turn/ddim_latents
max_number_of_frames: 24

n_timesteps: 999
prompt: Amazing quality, masterpiece, A car is turning on the road.
negative_prompt: ""
save_ddim_reconstruction: True